name: Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.9.4
            otp: 22.2
          - elixir: 1.10.4
            otp: 23.0
          - elixir: 1.13.0
            otp: 24.1
            dialyzer: true
    steps:
      - name: Install System Dependencies
        run: |
            sudo apt-get install -y --no-install-recommends \
            libxml2-dev \
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test --trace
      - name: Restore PLT cache
        uses: actions/cache@v2
        if: ${{ matrix.dialyzer }}
        id: plt_cache
        with:
          key: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-plt
          path: |
            priv/plts
      # Create PLTs if no cache was found
      - name: Create PLTs
        if: ${{ matrix.dialyzer && steps.plt_cache.outputs.cache-hit != 'true' }}
        run: mix dialyzer --plt
      - name: Run dialyzer
        if: ${{ matrix.dialyzer }}
        run: mix dialyzer